### ISSUE TITLE
[1.0.3] Client crash when using iChuns sync shell

### ISSUE THREAD

**Issue by ruyanve** [Ivorforce/IvToolkit#2]
There's this zoom-out animation when using a sync shell, that's when the client crashed. Server is fine.

Forge 10.13.2.1291
IVToolkit: 1.0.3
RC: 0.9.4
Sync: 4.0.0
iChunUtil: 4.1.3
Full crash log: http://pastebin.com/YHnAK5SZ

**Comment by Ivorforce** [comment]
Should be fixed in the latest nightly of Recurrent Complex, and likewise in the next release.
Thanks for reporting :)
