### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ShadeyWolf294** [Ivorforce/IvToolkit#5]
Hi,
I wasn't too sure where to put this issue, but someone told me to send it to you.
I have no idea what's going on. But whenever I kill a Mo' Creature, I'm disconnected from the server and get a message saying "Internal Server Error". If I kill a vanilla creature, this error doesn't occur. Here's the crash report:

http://pastebin.com/VzRvGH7G

Any help? Thanks! :D

**Comment by Ivorforce** [comment]
Please resubmit this in Ye Gamol Chattels - the error occurs in there.
