### ISSUE TITLE
cannot be cast to

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Ivorforce/IvToolkit#6]
http://hastebin.com/maneguheya.md
RecurrentComplex-0.9.6.3.n322.jar
IvToolkit-1.2.1.n94.jar

**Comment by Ivorforce** [comment]
hastebin file seems to be missing - it redirects to the homepage.

**Comment by SvEgiiVEteR** [comment]
@Ivorforce so long ago sent ..... does not work. crash has not survived ((

**Comment by Ivorforce** [comment]
I'll be hoping then that the crash was simply on some unstable nightly. Just make a new issue when it occurs again :)

**Comment by SvEgiiVEteR** [comment]
Yes it is possible, more often crash if the add and update mode. I have to re-create each time the card .. but this is a common problem. may be the oldest crash was associated with it.

**Comment by Ivorforce** [comment]
Well, if you can still recreate it with the latest nightlies I'll need a new crash report, because it doesn't happen on my end.
