### ISSUE TITLE
Crash in Mystcraft profiling with v1.2.1

### ISSUE THREAD

**Issue by xJon** [Ivorforce/IvToolkit#7]
http://pastebin.com/fkRcExUS
Any idea what's the cause?

**Comment by Ivorforce** [comment]
ReC 0.9.7 will be released tomorrow - and IvToolkit 1.2.1 had to break backwards compatibility with ReC 0.9.6.3. Just use 1.2 until then.

**Comment by xJon** [comment]
:+1:
