### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Ivorforce/IvToolkit#8]
LIB_IvToolkit-1.2.1
https://gist.github.com/fd0fc895f35e1a1fb049ea3a80421ed5
on server. client works

**Comment by Ivorforce** [comment]
ReC 0.9.6.3 and IvToolkit 1.2.1 are incompatible - use 1.2 until the next release (today). See also https://github.com/Ivorforce/IvToolkit/issues/7.

**Comment by SvEgiiVEteR** [comment]
@Ivorforce Thank you. and then I can use? https://drone.io/github.com/Ivorforce/RecurrentComplex/files
